### ISSUE TITLE
problem with train.py

### ISSUE THREAD

**Issue by eliwilner** [b05902062/TDConvED#1]
Hi,

I'm trying to execute `python3 train.py` after all data has been downloaded and created all json files. I'm getting an error of:

`using cuda:0
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    train(args)
  File "train.py", line 24, in train
    train_meta=msr_vtt_dataset(args.train_vocab,args.image_dir,"train",args.batch_size,shuffle=True)
  File "/home/ubuntu/TDConvED/src/data_loader.py", line 26, in __init__
    sen_in,video_id=zip(*combo)
ValueError: not enough values to unpack (expected 2, got 0)`  

However, it seems that train.py can uses defaults values so I don't need to pass them.

Any idea why it is happening?

**Comment by eliwilner** [comment]
I just saw that my train_vocab.json looks like this:

`{"w2i": {"<pad>": 0, "<sos>": 1, "<eos>": 2, "<unk>": 3}, "i2w": {"0": "<pad>", "1": "<sos>", "2": "<eos>", "3": "<unk>"}, "ref": {}, "video_id": [], "sen_in": []}
`
Why is it so empty? I'm assuming this is the reason for the error I've mentioned.

Thanks

**Comment by b05902062** [comment]
I see. I will check for that.

**Comment by b05902062** [comment]
I think maybe you didn't successfully download the videos. Can you check whether there is any images under TDConvED/data/msr_vtt/train/ folder? If not, maybe try to reinstall pytube with
$pip3 install pytube3
And see whether it works.

**Comment by eliwilner** [comment]
Thanks

**Comment by eliwilner** [comment]
So, I tried to reinstall via `pip3 install pytube3` but the folder TDConvED/data/msr_vtt/train/  still seems to be empty....

**Comment by b05902062** [comment]
When you run this two lines in python3, what is the output?
$python3
from acquire_images import download_video
download_video('https://www.youtube.com/watch?v=3nmcs4G_KLw','../data/','robot')

**Comment by eliwilner** [comment]
It says: two many requests
I'm trying to run it on aws EC2, could that be a problem?

**Comment by b05902062** [comment]
Seems like the ip has probably been blocked by YouTube for sending too many requests. Maybe I will add a simple checkpoint later so that people don't need to train from scratch by themself.

**Comment by b05902062** [comment]
I have added a link for downloading a sample checkpoint at the last part of readme.md.
