### ISSUE TITLE
Custom Video

### ISSUE THREAD

**Issue by eliwilner** [b05902062/TDConvED#2]
Hello again,

Is it possible to generate caption for a local video (on my desktop) and not a YouTube one?

**Comment by b05902062** [comment]
Yes, it is. Just as I did in the last part of readme. However it might not work well on some videos.

**Comment by amil-rp-work** [comment]
@b05902062 
Is there a link to download pre-trained models for inference on custom video?

**Comment by takuyara** [comment]
@amil-rp-work https://drive.google.com/file/d/1SCoV2QRMQ-iJ7Vu9JygEnaGvRl0fX80v/view?usp=sharing
It is in the comments in the last sample code of the readme.md.
